name: Run newday data

on:
  [push]
  # schedule:
  #   # 시간이 UTC 기준이므로 15시가 한국의 자정!
  #   - cron: '15 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update daily data to DB
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: .github/actions/update_video_list/package-lock.json

      - name: Install npm dependencies
        run: |
          pushd .github/actions/update_video_list
          npm ci
          npm install puppeteer
          npm install jsdom

      - name: Update daily data
        run: |
          pushd .github/actions/update_video_list
          npm run start
